Installing [tensorly](http://tensorly.org/)

In [ ]:
!pip install -U tensorly

In [68]:
import tensorly as tl
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
from tensorly import decomposition

Define a NumPy array of 3 dimensions, which here represents 3 qubits state.

In [69]:
tensor = tl.tensor([0, 1, 1, 0.05, 0, 2, 2, 0, 0, 1, 1, 0.05, 0, 2, 2, -0.1]).reshape(2,2,2,2)
print(tensor)

[[[[0.000 1.000]
   [1.000 0.050]]

  [[0.000 2.000]
   [2.000 0.000]]]


 [[[0.000 1.000]
   [1.000 0.050]]

  [[0.000 2.000]
   [2.000 -0.100]]]]


In [77]:
tt = decomposition.tensor_train(tensor, rank=2)
tt.factors

[array([[[-0.707, -0.707],
         [-0.707, 0.707]]]),
 array([[[-0.447, -0.717],
         [-0.894, 0.359]],
 
        [[-0.000, -0.000],
         [-0.000, -0.598]]]),
 array([[[0.729, 0.683],
         [-0.684, 0.730]],
 
        [[0.000, 0.000],
         [0.027, 0.026]]]),
 array([[[-2.162],
         [2.331]],
 
        [[2.307],
         [2.141]]])]

In [78]:
print(tt.to_tensor())

[[[[0.000 1.000]
   [1.000 0.050]]

  [[0.000 2.000]
   [2.000 0.000]]]


 [[[0.000 1.000]
   [1.000 0.050]]

  [[-0.000 2.000]
   [2.000 -0.100]]]]


In [79]:
np.allclose(tt.to_tensor(), tensor)

True